[package]
name = "rbxlx2vmf"
version = "0.1.4"
edition = "2021"
publish = false

[dependencies]
clap = { version = "4.5.40" }
roxmltree = "0.20.0"
serde_json = "1.0.140"
async-std = { version = "1.13.1", features = ["tokio1"] }
tokio = "1.45.1"