[package]
name = "rbxlx2vmf"
version = "0.1.4"
edition = "2021"
publish = false

[dependencies]
clap = { version = "4.4.16" }
roxmltree = "0.19.0"
serde_json = "1.0.111"
async-std = { version = "1.12.0", features = ["tokio1"] }
tokio = "1.35.1"